name: Elena Miniaeva
description: Jekyll Tutorial

collections:
  authors:
    output: true

defaults:
  - scope:
      path: "https://ull-mii-sytws-1920.github.io/elenaminyaeva-github-pages/"
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
theme: jekyll-theme-cayman
